baseurl = "/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Cyber Explore"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Exploring Technolgy And The Cyber World"
  mainSections = ["post","posts"]
  logo = "img/Cyber Explore.jpg" # Expecting square dimensions
  favicon = "img/Cyber Explore.ico"
  dateFormat = "January 2, 2006"
  commit = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "A.D.S"
  email = "shoremekunfiirekanmi762@gmail.com"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "channel/UCg2qPDuQRPkdyMi6sxr_jAQ?view_as=subscriber"
  soundcloud = "beatmaker"
  vk = "username"
  paypal = "username"
  500px = "shoremekunfiirekanmi762"
  codepen = "username"
  kaggle = "username"
  slack = "username"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "New Posts"
    name = "New Posts"
    weight = 2

[[menu.main]]
    parent = "New Posts"
    name = "Servers"
    url = "post/servers"
    weight = 1

[[menu.main]]
    parent = "New Posts"
    name = "Coding With VS Code"
    url = "post/2015-01-27-Coding with VS Code"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "post/2016-03-08-code-sample"
    weight = 3

[[menu.main]]
    name = "Hashtags"
    url = "tags"
    weight = 3

